[project]
name = "bootcamp"
version = "0.1.0"
description = "Enhanced Student Grade Visualization with Plotly"
readme = "README.md"
requires-python = ">=3.12"
 fatma-assignment
    "pandas",
    "plotly",

    "pandas", "plotly"
 main
]
